export const digitalCurrencies = [    
    { coin: 'ADA', description: 'Cardano', initialDate: '07/10/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'ANKR', description: 'ANKR', initialDate: '25/08/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'AXS', description: 'Axie Infinity Shard', initialDate: '01/04/2021', minimumTradingValue: 0, isActive: true },    
    { coin: 'BAND', description: 'Band Protocol', initialDate: '25/08/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'BAT', description: 'Basic Attention token', initialDate: '25/05/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'BCH', description: 'Bitcoin Cash', initialDate: '21/08/2017', minimumTradingValue: 0, isActive: true },
    { coin: 'BTC', description: 'Bitcoin', initialDate: '12/06/2013', minimumTradingValue: 0, isActive: true },
    { coin: 'CHZ', description: 'Chiliz', initialDate: '14/07/2020', minimumTradingValue: 0, isActive: true },
    { coin: 'ENJ', description: 'Enjin', initialDate: '25/05/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'ETH', description: 'Ethereum', initialDate: '12/12/2018', minimumTradingValue: 0, isActive: true },
    { coin: 'GRT', description: 'The Graph', initialDate: '25/05/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'LINK', description: 'CHAINLINK', initialDate: '10/12/2020', minimumTradingValue: 0, isActive: true },
    { coin: 'LTC', description: 'Litecoin', initialDate: '23/08/2013', minimumTradingValue: 0, isActive: true },
    { coin: 'MANA', description: 'MANA ', initialDate: '25/05/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'MATIC', description: 'Polygon', initialDate: '25/08/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'MCO2', description: 'MCO2', initialDate: '04/02/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'OMG', description: 'Omg Network', initialDate: '25/08/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'PAXG', description: 'PAX Gold', initialDate: '04/08/2020', minimumTradingValue: 0, isActive: true },
    { coin: 'USDC', description: 'USD Coin', initialDate: '26/05/2020', minimumTradingValue: 0, isActive: true },
    { coin: 'WBTC', description: 'Wrapped Bitcoin', initialDate: '25/08/2021', minimumTradingValue: 0, isActive: true },
    { coin: 'WBX', description: 'WiBX', initialDate: '14/07/2020', minimumTradingValue: 0, isActive: true },
    { coin: 'XRP', description: 'XRP', initialDate: '10/10/2018', minimumTradingValue: 0, isActive: true },    
]